'use strict';
const D = JSON.parse(document.getElementById('model-data').textContent);
const tables = Object.fromEntries(D.sources.tables.map(t => [t.name,t]));
const metrics = Object.fromEntries(D.registry.metrics.map(m => [m.metric_id,m]));
const agents = Object.fromEntries(D.agents.agents.map(a => [a.agent_id,a]));
const processes = Object.fromEntries(D.processes.map(p => [p.process_id,p]));
const main = document.getElementById('content');
const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc = encodeURIComponent;
const text = v => v === null || v === undefined ? 'Sin dato' : typeof v === 'object' ? JSON.stringify(v) : String(v);
const money = n => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(n/100);
const num = n => new Intl.NumberFormat('es-MX',{maximumFractionDigits:3}).format(n);
const value = m => !m || m.status !== 'measured' ? 'Sin evidencia' : m.unit === 'MXN_cents' ? money(m.value) : m.unit === 'ratio' ? num(m.value*100)+' %' : num(m.value)+(m.unit === 'hours' ? ' h' : '');
const tag = (s,label=s) => `<span class="tag ${e(s)}">${e(label)}</span>`;
const link = (type,id,label) => `<a href="#${type}/${enc(id)}">${e(label || id)}</a>`;
const chips = (type,ids) => `<div class="chip-links">${(ids||[]).map(id => link(type,id,type==='sources' ? tables[id]?.label||id : type==='metrics' ? metrics[id]?.label||id : type==='agents' ? agents[id]?.profile.name||id : processes[id]?.title||id)).join('')}</div>`;
const head = (small,title,intro,action='') => `<div class="page-heading"><div><p class="eyebrow">${e(small)}</p><h1>${e(title)}</h1><p class="intro">${e(intro)}</p></div>${action}</div>`;
const table = (cols,rows) => `<div class="table-scroll" tabindex="0"><table><thead><tr>${cols.map(c=>`<th scope="col">${e(c)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const empty = s => `<div class="empty">${e(s)}</div>`;
const titleOf = t => tables[t]?.label || t;
const sourceKind = t => t.kind==='physical_source' ? 'Fuente' : 'Derivada';
function recordHref(t,row) { return '#record/'+enc(t.name)+'/'+enc(JSON.stringify(t.logical_key.map(k=>row[k]))); }
function sourceRecord(tableName,id,label) {
  const t=tables[tableName]; const row=t?.rows.find(r=>String(r[t.logical_key[0]])===String(id));
  return row ? `<a href="${recordHref(t,row)}">${e(label||id)}</a>` : e(label||id);
}
function evidenceTable(items) {
  return table(['Tabla / registro','Campo','Valor observado','Versión'],items.filter(r=>r.table||r.entity_type).map(r=>[
    sourceRecord(r.table||r.entity_type,r.record_id||r.entity_id,`${r.table||r.entity_type} / ${r.record_id||r.entity_id}`),
    e(r.field||Object.keys(r.fields||{}).join(', ')),e(text(r.value!==undefined?r.value:r.fields)),e(text(r.version))]));
}
function caseCard(c) {
  return `<a class="case" href="#decision/${enc(c.action_id)}"><div class="case-top">${tag(c.priority)}<code>${e(c.action_id)}</code></div><strong>${e(c.title)}</strong><p>${e(c.recommended_next_step)}</p><small>${e(c.owner_role)}${c.amount_at_risk_cents!==null?' · '+money(c.amount_at_risk_cents):''}</small></a>`;
}
function metricStat(id) { const m=metrics[id]; return `<div class="stat"><small>${e(m.label)}</small><strong>${e(value(m))}</strong>${link('metrics',id,'Ver cálculo y fuente ↗')}</div>`; }
function overview() {
  const ops=D.operations.decisions;
  const first=ops.find(c=>(c.metric_ids||[]).includes('M-WIP-WAITING-PARTS'))||ops[0];
  main.innerHTML=head('Corte de operación / muestra sintética','Lo que necesita revisión.','Empieza por las prioridades y abre su evidencia. Cada cifra se puede rastrear hasta los registros que la alimentan.','<a class="button" href="#decisions">Abrir la cola de revisión →</a>')+
    `<div class="stats">${['M-WIP-OPEN','M-WIP-WAITING-PARTS','M-AR-RECEIVABLE','M-FLEET-SLA-RISK'].map(metricStat).join('')}</div>`+
    `<div class="two-col"><section class="panel"><div class="section-top"><h2>Prioridades del corte</h2><a href="#decisions">${ops.length} señales por revisar ↗</a></div><p class="small muted">Reglas sobre la población completa. Un registro puede generar más de una señal; los importes no se suman como oportunidad comercial.</p><div class="list">${ops.slice(0,5).map(caseCard).join('')||empty('Ninguna regla activó una prioridad en este corte.')}</div></section>`+
    `<div><section class="panel"><p class="eyebrow">Cobertura visible</p><h2>Abre los datos que sostienen el análisis.</h2><div class="kv"><dt>Tablas fuente</dt><dd>${D.sources.physical_source_tables}</dd><dt>Tablas derivadas</dt><dd>${D.sources.derived_marts}</dd><dt>Definiciones de métricas</dt><dd>${D.registry.metrics.length}</dd><dt>Roles de agentes</dt><dd>${D.agents.agents.length}</dd><dt>Procesos especificados</dt><dd>${D.processes.length}</dd></div><p>${link('sources','work_orders','Explorar órdenes y relaciones →')}</p></section>`+
    `<section class="panel section"><p class="eyebrow">Trazabilidad en un caso</p><h2>Del registro a la revisión</h2><div class="steps"><a href="#sources/work_orders"><strong>1. Fuente</strong>Orden y relaciones</a><a href="#metrics/M-WIP-WAITING-PARTS"><strong>2. Cálculo</strong>Definición y población</a><a href="#agents/operations_controller"><strong>3. Agente</strong>Lecturas y sustento</a><a href="#${first?'decision/'+enc(first.action_id):'decisions'}"><strong>4. Revisión</strong>Siguiente paso y evidencia</a></div><p class="small muted">Las corridas actuales por reglas se identifican como tales. El motor también admite Codex; una configuración de rol no acredita una inferencia.</p></section></div></div>`+
    `<section class="panel section"><div class="section-top"><h2>Recepciones y entregas por fecha</h2>${link('sources','mart_daily_operations','Abrir la tabla de esta gráfica ↗')}</div><img class="chart" src="charts/flujo_diario.svg" alt="Recepciones y entregas diarias del historial sintético"><p class="small muted">La cohorte ficticia de demostración no acredita demanda, productividad ni tendencia real.</p></section>`;
}
function decisions() {
  main.innerHTML=head('Agenda de revisión','Prioridades y propuestas','La cola OPS revisa todas las filas con reglas declaradas. Las propuestas AGT conservan la evidencia de cada corrida acotada.','<a class="button" href="Seguimiento.xlsx">Descargar seguimiento Excel ↗</a>')+
    `<div class="toolbar"><label>Buscar por ID, título o evidencia<input id="case-search" type="search" placeholder="Ej. WO-003 o factura"></label><label>Origen<select id="case-origin"><option value="OPS">Prioridades operativas (OPS)</option><option value="AGT">Propuestas de agentes (AGT)</option><option value="">Ambas colas</option></select></label><label>Prioridad<select id="case-priority"><option value="">Todas</option>${['P1','P2','P3','review'].map(p=>`<option>${p}</option>`).join('')}</select></label></div><p id="case-count" class="small muted" aria-live="polite"></p><div id="cases-list"></div><details><summary>Reglas de prioridad y cobertura de lectura</summary><pre>${e(JSON.stringify(D.operations.policy,null,2))}</pre><pre>${e(JSON.stringify(D.operations.coverage,null,2))}</pre></details>`;
  const render=()=>{const q=document.getElementById('case-search').value.toLowerCase(),origin=document.getElementById('case-origin').value,p=document.getElementById('case-priority').value;
    const rows=D.decisions.filter(c=>(!origin||c.action_id.startsWith(origin))&&(!p||c.priority===p)&&JSON.stringify(c).toLowerCase().includes(q));
    document.getElementById('case-count').textContent=`${rows.length} señales. Estado inicial: pendiente de revisión humana.`;
    document.getElementById('cases-list').innerHTML=rows.length?table(['Prioridad','Caso / siguiente paso','Rol sugerido','Importe relacionado'],rows.map(c=>[tag(c.priority),`${link('decision',c.action_id,c.title)}<p class="small muted">${e(c.recommended_next_step)}</p>`,e(c.owner_role),c.amount_at_risk_cents===null?'No aplica':e(money(c.amount_at_risk_cents))])):empty('No hay coincidencias. Ajusta los filtros.');
  }; ['case-search','case-origin','case-priority'].forEach(id=>document.getElementById(id).addEventListener('input',render)); render();
}
function decision(id) {
  const c=D.decisions.find(x=>x.action_id===id); if(!c){main.innerHTML=empty('No existe esta propuesta.');return;}
  main.innerHTML=head(c.action_id,c.title,c.owner_role,'<a class="button" href="#decisions">← Volver a prioridades</a>')+
    `<div class="two-col"><section class="panel">${tag(c.priority)} ${tag('unknown','Pendiente de revisión')}<h2 class="section">Por qué revisarlo</h2><p>${e(c.why_now)}</p><h3>Siguiente paso sugerido</h3><p class="definition">${e(c.recommended_next_step)}</p><p class="small muted">Importe relacionado: ${c.amount_at_risk_cents===null?'no calculado':e(money(c.amount_at_risk_cents))+'. No equivale a ahorro o ingreso recuperado.'}</p><h3>Registros que sustentan el caso</h3>${evidenceTable(c.evidence||[])}
    ${(c.drafts||[]).length?'<h3 class="section">Borradores de la corrida</h3>'+c.drafts.map(d=>'<div class="notice"><strong>'+e(d.kind)+'</strong><p>'+e(d.text)+'</p><small>Requiere revisión humana. No enviado.</small></div>').join(''):''}
    ${(c.missing_evidence||[]).length?'<h3 class="section">Información pendiente</h3><ul>'+c.missing_evidence.map(s=>'<li>'+e(s)+'</li>').join('')+'</ul>':''}</section>
    <div><section class="panel"><h2>Cálculos relacionados</h2>${chips('metrics',c.metric_ids)}<h3 class="section">Procesos</h3>${chips('processes',c.process_ids)}<h3 class="section">Seguimiento humano</h3><ol class="small"><li>Copiar el libro fuera de esta carpeta.</li><li>Asignar responsable y fecha después de revisar la evidencia.</li><li>Registrar el resultado y su respaldo documental.</li><li>Importar la copia con <code>studio-review</code>.</li></ol><a class="button" href="Seguimiento.xlsx">Abrir libro de seguimiento ↗</a><p class="small muted">${e(c.action_id)} es el ID estable que encontrarás en el libro.</p></section>
    <section class="panel section"><h3>Identidad de fuente</h3><p class="mono">${e(D.metadata.snapshot_id)}</p><p class="small">Corte: ${e(D.metadata.as_of)}. La revisión conserva esta identidad; una anotación no cambia la fuente.</p></section></div></div>`;
}
function sources(name) {
  if(name&&!tables[name]){main.innerHTML=empty('Esta tabla no existe en el corte.');return;}
  const t=tables[name]||tables.work_orders;
  main.innerHTML=head('Fuentes / '+sourceKind(t),t.label,t.grain,`<a class="button" href="${e(t.source_file)}">Descargar esta tabla CSV ↗</a>`)+
    `<div class="toolbar"><label>Tabla<select id="source-select">${D.sources.tables.map(x=>`<option value="${e(x.name)}" ${x.name===t.name?'selected':''}>${e(x.label)} · ${x.row_count} filas · ${sourceKind(x)}</option>`).join('')}</select></label><label>Buscar en todos los campos<input id="source-search" type="search" placeholder="ID, estado, cliente…"></label></div>
    <section class="panel"><div class="section-top"><h2>${e(t.name)}</h2>${tag('measured',sourceKind(t)+' · '+t.row_count+' filas')}</div><p class="small muted">Responsable propuesto: ${e(t.owner_role)} · Clave física: ${e(t.primary_key.join(' + ')||'No impuesta en el mart')} · Clave lógica: ${e(t.logical_key.join(' + '))}</p>
    <div id="source-rows"></div><div class="pager"><span id="source-count" aria-live="polite"></span><div><button id="prev">← Anterior</button> <button id="next">Siguiente →</button></div></div></section>
    <section class="panel section"><h2>Qué alimenta esta tabla</h2>${chips('metrics',t.metric_ids)}<p class="small muted">${e(t.limitations)}</p><details><summary>Diccionario de campos, nulos y relaciones</summary>${table(['Campo','Tipo SQLite','Permite nulo','Nulos en corte','Descripción'],t.fields.map(f=>[e(f.name),e(f.type),f.nullable?'Sí':'No',e(f.null_count),e(f.description)]))}<h3 class="section">Relaciones verificadas por la base</h3>${t.relationships.length?table(['Campos de origen','Tabla relacionada','Campos destino'],t.relationships.map(r=>[e(r.from_fields.join(', ')),link('sources',r.target_table,titleOf(r.target_table)),e(r.to_fields.join(', '))])):'<p class="small">Esta tabla no tiene claves foráneas físicas.</p>'}</details></section>`;
  document.getElementById('source-select').addEventListener('change',ev=>location.hash='#sources/'+enc(ev.target.value));
  let page=0,sort=t.logical_key[0],direction=1, filtered=[];
  function render(){const q=document.getElementById('source-search').value.toLowerCase();filtered=t.rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)).sort((a,b)=>{let x=a[sort],y=b[sort];return direction*(typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''),'es',{numeric:true}));});
    const max=Math.max(0,Math.ceil(filtered.length/25)-1);page=Math.min(page,max);const rows=filtered.slice(page*25,page*25+25);
    document.getElementById('source-rows').innerHTML=rows.length?`<div class="table-scroll" tabindex="0"><table class="data-table"><thead><tr><th>Ficha</th>${t.fields.map(f=>`<th scope="col" aria-sort="${f.name===sort?(direction===1?'ascending':'descending'):'none'}"><button data-sort="${e(f.name)}">${e(f.name)} ${f.name===sort?(direction===1?'↑':'↓'):''}</button></th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr><td><a href="'+recordHref(t,r)+'">Abrir →</a></td>'+t.fields.map(f=>{const rel=t.relationships.find(k=>k.from_fields.length===1&&k.from_fields[0]===f.name);return '<td>'+(rel&&r[f.name]!==null?sourceRecord(rel.target_table,r[f.name]):e(text(r[f.name])))+'</td>';}).join('')+'</tr>').join('')}</tbody></table></div>`:empty('Ningún registro coincide con la búsqueda.');
    document.getElementById('source-count').textContent=filtered.length?`${page*25+1}–${Math.min((page+1)*25,filtered.length)} de ${filtered.length} filas`:'0 filas';
    document.getElementById('prev').disabled=page===0;document.getElementById('next').disabled=page>=max;
    document.querySelectorAll('[data-sort]').forEach(b=>b.addEventListener('click',()=>{direction=b.dataset.sort===sort?-direction:1;sort=b.dataset.sort;render();}));
  }
  document.getElementById('source-search').addEventListener('input',()=>{page=0;render();});document.getElementById('prev').onclick=()=>{page--;render();};document.getElementById('next').onclick=()=>{page++;render();};render();
}
function record(name,keyText) {
  const t=tables[name];let key;try{key=JSON.parse(keyText);}catch{key=[];}
  const row=t?.rows.find(r=>t.logical_key.every((k,i)=>r[k]===key[i]));if(!row){main.innerHTML=empty('El registro no existe en este corte.');return;}
  const id=key.join(' / ');const related=[];
  for(const other of D.sources.tables){for(const fk of other.relationships.filter(f=>f.target_table===name)){
    const matches=other.rows.filter(r=>fk.from_fields.every((f,i)=>r[f]!==null&&r[f]===row[fk.to_fields[i]]));
    if(matches.length)related.push({t:other,rows:matches,via:fk.from_fields.join(' + ')});
  }}
  // Polymorphic lifecycle reference is contract-validated; it is not a physical SQL FK.
  const events=tables.lifecycle_events.rows.filter(r=>r.entity_type===name&&r.entity_id===row.id).sort((a,b)=>a.at.localeCompare(b.at));
  const cases=D.decisions.filter(c=>(c.evidence||[]).some(r=>(r.table||r.entity_type)===name&&String(r.record_id||r.entity_id)===String(row.id)));
  main.innerHTML=head(t.label,id,'Ficha de origen con relaciones físicas y evidencia del corte.',`<a class="button" href="#sources/${enc(name)}">← Tabla completa</a>`)+
    `<div class="two-col"><section class="panel"><h2>Valores de origen</h2>${table(['Campo','Valor'],t.fields.map(f=>{const rel=t.relationships.find(x=>x.from_fields.length===1&&x.from_fields[0]===f.name);return [e(f.name),rel&&row[f.name]!==null?sourceRecord(rel.target_table,row[f.name]):e(text(row[f.name]))];}))}</section><div><section class="panel"><h2>Revisiones relacionadas</h2><div class="list">${cases.map(caseCard).join('')||'<p class="muted small">Este registro no activó una revisión ni fue citado por una propuesta en el corte. No equivale a certificación de salud.</p>'}</div><h3 class="section">Métricas que leen esta tabla</h3>${chips('metrics',t.metric_ids)}</section></div></div>`+
    `<section class="panel section"><h2>Registros vinculados</h2>${related.length?related.map(x=>`<details open><summary>${e(x.t.label)} · ${x.rows.length} · por ${e(x.via)}</summary>${table(['Abrir ficha',...x.t.fields.slice(0,9).map(f=>f.name)],x.rows.map(r=>[`<a href="${recordHref(x.t,r)}">${e(x.t.logical_key.map(k=>r[k]).join(' / '))} ↗</a>`,...x.t.fields.slice(0,9).map(f=>e(text(r[f.name])))]))}</details>`).join(''):'<p>No hay registros que apunten a esta fila mediante una clave foránea.</p>'}</section>`+
    `<section class="panel section"><h2>Historial observado del caso</h2>${events.length?table(['Fecha UTC','Desde','Hacia','Actor registrado','ID de instancia del proceso'],events.map(r=>[e(r.at),e(r.from_state),e(r.to_state),e(r.actor),e(r.process_id)])):'<p class="muted">No se aportaron eventos para este caso; no se reconstruye su recorrido a partir del estado actual.</p>'}</section>`;
}
function metricPage(id) {
  if(id&&!metrics[id]){main.innerHTML=empty('Esta métrica no existe en el catálogo.');return;}
  const m=metrics[id]||D.registry.metrics[0];
  main.innerHTML=head('Definiciones / cálculo reproducible','Métricas del taller','Cada resultado conserva su unidad, población, consultas y tablas de origen. Una fuente vacía o incompleta no se interpreta como buen desempeño.','<a class="button" href="Metricas_y_fuentes.xlsx">Catálogo Excel ↗</a>')+
    `<div class="toolbar"><label>Elegir métrica<select id="metric-select">${D.registry.metrics.map(x=>`<option value="${e(x.metric_id)}" ${x.metric_id===m.metric_id?'selected':''}>${e(x.metric_id+' · '+x.label)}</option>`).join('')}</select></label><label>Buscar en el catálogo<input id="metric-search" type="search" placeholder="Cobranza, ciclo, partes…"></label></div>
    <div class="two-col"><section class="panel"><p class="eyebrow">${e(m.metric_id)}</p><h2>${e(m.label)}</h2><div class="metric-value">${e(value(m))}</div>${tag(m.status,m.status==='measured'?'Calculada sobre el corte':'No calculable con esta evidencia')}<p class="definition">${e(m.definition_es||m.definition)}</p>
    <dl class="kv"><dt>Unidad</dt><dd>${e(m.unit)}</dd><dt>Grano</dt><dd>${e(m.grain)}</dd><dt>Numerador / observaciones</dt><dd>${e(text(m.numerator))}</dd><dt>Denominador / población</dt><dd>${e(text(m.denominator))}</dd><dt>Rol propuesto</dt><dd>${e(m.owner_role)}</dd></dl><p class="small">${e(m.formula_es||'La consulta inferior define el cálculo; las medianas usan las observaciones elegibles.')}</p><p class="small muted">${e(m.population_es||'')}</p>
    ${m.reason?'<div class="notice">'+e(m.reason)+'</div>':''}<h3>Cómo usarla</h3><p>${e(m.decision_use_es||m.limitations_es||m.limitations)}</p><p class="small muted">${e(m.limitations_es||m.limitations)}</p><p class="small muted">${e(m.null_policy_es||'Sin evidencia suficiente, el resultado permanece desconocido.')}</p></section>
    <section class="panel"><h2>De dónde sale</h2>${chips('sources',m.source_tables)}<p class="small mono">${e(m.source_fields.join(', '))}</p><h3 class="section">Consulta de lectura</h3><pre>${e(m.query||'No hay consulta ejecutable: falta una fuente versionada.')}</pre><p class="small muted">Los parámetros ? usan el corte ${e(D.metadata.as_of)}. La consulta pertenece al código; no se ejecuta SQL escrito desde esta pantalla.</p><h3>Procesos que la usan</h3>${chips('processes',m.process_ids)}</section></div>
    <section class="panel section"><h2>Muestra de valores de origen</h2><p class="small muted">${m.evidence_rows.length} registros de muestra sobre ${m.evidence_total} filas fuente. La muestra incluye fuentes de entrada; no es la lista exacta de casos elegibles para cada fórmula. Abre las tablas completas y la consulta para reproducirla.</p>${evidenceTable(m.evidence_rows)}</section><section class="section"><h2>Catálogo completo · ${D.registry.metrics.length} definiciones</h2><div id="metric-index"></div></section>`;
  document.getElementById('metric-select').onchange=ev=>location.hash='#metrics/'+enc(ev.target.value);
  const filter=()=>{const q=document.getElementById('metric-search').value.toLowerCase();const rows=D.registry.metrics.filter(x=>[x.metric_id,x.label,x.domain,x.definition_es].join(' ').toLowerCase().includes(q));document.getElementById('metric-index').innerHTML=table(['Métrica','Resultado','Estado','Dominio','Fuentes'],rows.map(x=>[link('metrics',x.metric_id,x.label),e(value(x)),tag(x.status,x.status==='measured'?'Calculada':'Desconocida'),e(x.domain),chips('sources',x.source_tables)]));};document.getElementById('metric-search').oninput=filter;filter();
}
function agentPage(id) {
  if(id&&!agents[id]){main.innerHTML=empty('Este agente no existe en el contrato.');return;}
  const a=agents[id]||D.agents.agents[0],p=a.profile,r=a.current_run;
  const native=r.status==='current'&&r.model_invoked&&r.execution_class==='native_codex';
  main.innerHTML=head('Roles / ejecución / evidencia','Mesa de agentes','Cada rol tiene un objetivo, herramientas de lectura y una salida revisable. Las corridas conservan la identidad de la base que consultaron.')+
    `<div class="toolbar"><label>Seleccionar rol<select id="agent-select">${D.agents.agents.map(x=>`<option value="${e(x.agent_id)}" ${x.agent_id===a.agent_id?'selected':''}>${e(x.profile.name)}</option>`).join('')}</select></label></div><div class="run-strip">${tag(r.status,r.status==='current'?'Fuente vigente para esta corrida':r.status)} · ${native?'Inferencia Codex registrada':'Reglas deterministas · sin inferencia de modelo en esta corrida'} · ${a.proposals.length} propuestas de revisión</div>
    <div class="two-col"><section class="panel"><p class="eyebrow">${e(a.agent_id)}</p><h2>${e(p.name)}</h2><p>${e(p.objective)}</p><h3>Fuentes autorizadas</h3>${chips('sources',p.scope)}<h3 class="section">Métricas del rol</h3>${chips('metrics',a.contract.metric_ids)}<h3 class="section">Salida requerida</h3><p>${e(p.required_deliverable)}</p><h3>Criterios</h3><ul>${p.criteria.map(s=>'<li>'+e(s)+'</li>').join('')}</ul><h3>Procesos</h3>${chips('processes',a.contract.processes)}</section>
    <section class="panel"><h2>Lecturas y trazabilidad</h2><p class="small">Herramientas permitidas:</p><div class="chip-links">${p.allowed_read_tools.map(x=>'<code>'+e(x)+'</code>').join(' · ')}</div><p class="small muted">La inspección de casos y la selección de evidencia están acotadas a 12 registros/referencias por llamada. Los agregados de métricas leen su población definida completa.</p><ol class="trace">${(r.tool_trace||[]).map(x=>'<li><strong>'+e(x.event||x.tool||x.status)+'</strong><br><span class="mono">'+e(Object.entries(x).filter(([k])=>!['event'].includes(k)).map(([k,v])=>k+': '+text(v)).join(' · '))+'</span></li>').join('')||'<li>No hay traza disponible.</li>'}</ol><p class="mono">SHA-256: ${e(r.source_hash)}</p>${r.run_path?`<p class="small"><a href="${e(r.run_path)}/result.json">Resultado completo</a> · <a href="${e(r.run_path)}/tool_trace.jsonl">Traza JSONL</a> · <a href="${e(r.run_path)}/input_packet.json">Paquete de entrada</a></p>`:''}</section></div>
    <section class="section"><h2>Propuestas fundamentadas de esta corrida</h2><div class="list">${a.proposals.map(caseCard).join('')||empty('Sin propuestas vigentes para esta corrida.')}</div></section>`;
  document.getElementById('agent-select').onchange=ev=>location.hash='#agents/'+enc(ev.target.value);
}
function processPage(id) {
  if(id&&!processes[id]){main.innerHTML=empty('Esta definición de proceso no existe. Los IDs de instancia del historial no son definiciones.');return;}
  const p=processes[id]||D.processes[0];
  main.innerHTML=head('Proceso / responsabilidades',p.title,p.purpose)+
    `<div class="tabs-list">${D.processes.map(x=>`<a class="${x.process_id===p.process_id?'active':''}" href="#processes/${enc(x.process_id)}">${e(x.title)}</a>`).join('')}</div><div class="two-col"><section class="panel"><h2>Recorrido y evidencia esperada</h2><p class="small muted">Hipótesis de trabajo documentada; el proceso real y las responsabilidades necesitan validación con el taller.</p><dl class="kv"><dt>Disparador</dt><dd>${e(p.scope?.trigger)}</dd><dt>Fin del proceso</dt><dd>${e(p.scope?.end)}</dd><dt>Responsable funcional</dt><dd>${e(p.accountable_owner)}</dd></dl><h3 class="section">Tablas del proceso</h3>${chips('sources',p.entities)}<h3 class="section">Métricas</h3>${chips('metrics',p.metrics)}<h3 class="section">Agentes</h3>${chips('agents',p.agents)}</section><section class="panel"><h2>Roles y responsabilidades</h2>${table(['Rol','Responde por'],(p.roles||[]).map(r=>[e(r.label),e((r.accountable_for||[]).join(', '))]))}<p><a href="processes/${e(p.process_id)}.md">SOP, RACI y excepciones ↗</a></p><p><a href="processes/${e(p.process_id)}.json">Especificación estructurada ↗</a></p></section></div>
    <section class="panel section"><h2>Mapa de actividades y decisiones</h2><div class="process-map" tabindex="0"><img src="processes/${e(p.process_id)}.svg" alt="Mapa de ${e(p.title)}"></div><details><summary>Leer actividades en una tabla</summary>${table(['Actividad','Tipo','Responsable','Evidencia'],(p.nodes||[]).map(n=>[e(n.label),e(n.type),e(n.owner),e(text(n.evidence_ids))]))}</details><details><summary>Controles y decisiones definidos</summary><pre>${e(JSON.stringify({controls:p.controls,decisions:p.decisions,evidence:p.evidence},null,2))}</pre></details></section>`;
}
function delivery() {
  main.innerHTML=head('Entrega / operación del análisis','Archivos para trabajar','La base, los libros y las definiciones pueden inspeccionarse sin un servicio en línea. El recibo permite detectar cambios en la entrega.')+
    `<div class="files">${[['Milenio_Analisis.xlsx','Libro completo de datos','36 hojas con fuentes, análisis y conciliación'],['Metricas_y_fuentes.xlsx','Catálogo de métricas y fuentes','31 métricas, poblaciones, SQL y diccionario de campos'],['Seguimiento.xlsx','Libro de seguimiento humano','Copiar fuera de la entrega; asignar y documentar resultados'],['warehouse.sqlite','Base relacional SQLite','27 fuentes y seis tablas derivadas'],['schema.sql','Esquema SQL','Tipos, claves, índices y relaciones'],['receipt.json','Recibo de integridad','Hashes de todos los archivos sellados'],['specs/requirements.json','Matriz de requisitos','Procesos, fuentes, métricas, agentes y aceptación'],['specs/agent_operating_contract.json','Contrato de agentes','Métricas del rol, responsabilidades y límites']].map(([path,title,desc])=>`<a href="${path}"><strong>${title} ↗</strong><small>${desc}</small></a>`).join('')}</div>
    <section class="panel section"><h2>Reunión de revisión · 30 minutos</h2><ol><li><strong>5 min — Confirmar el corte:</strong> fuentes recibidas, filas, calidad y métricas desconocidas.</li><li><strong>10 min — Revisar prioridades:</strong> abrir cada registro, sus pagos, partes o eventos. Confirmar el motivo y descartar los casos que no apliquen.</li><li><strong>10 min — Definir seguimiento:</strong> asignar responsable, fecha y evidencia esperada en una copia de Seguimiento.xlsx.</li><li><strong>5 min — Cerrar:</strong> registrar notas e importar la revisión. Un siguiente corte debe comprobar la fuente y el resultado reportado.</li></ol></section>
    <section class="panel section"><h2>Generar, verificar y registrar revisiones</h2><pre>.venv/Scripts/python.exe -m milenio studio --output artifacts/nuevo-corte\n.venv/Scripts/python.exe -m milenio verify-studio --input artifacts/nuevo-corte\n.venv/Scripts/python.exe -m milenio studio-review --report artifacts/nuevo-corte --input private/Seguimiento_revisado.xlsx --reviewer "Nombre del revisor" --output private/revision-nueva</pre><p>El comando studio admite un snapshot completo de 25 CSV, eventos y vínculos explícitos bajo el contrato sintético. Para datos reales, la entrada privada actual admite órdenes, facturas, pagos e inventario: <code>client-template</code> y <code>client-analyze</code>. No completa automáticamente dominios ausentes.</p><p class="notice">Este estudio amplio todavía usa datos sintéticos y el corte fijo declarado. La importación privada de cuatro fuentes tiene otro contrato. No se han cargado registros reales de Taller Milenio, validado responsables ni ejecutado un piloto con el cliente.</p><p class="small">El modo opcional <code>studio --native</code> usa una sesión de Codex autenticada. La entrega mostrará inferencia sólo si existen corridas terminadas y verificadas para esa base.</p></section>`;
}
const names={overview:'Panorama',decisions:'Prioridades y revisión',decision:'Ficha de revisión',sources:'Tablas fuente',record:'Ficha de registro',metrics:'Métricas y cálculo',agents:'Mesa de agentes',processes:'Procesos y controles',delivery:'Archivos y uso'};
function route(){let parts;try{parts=location.hash.slice(1).split('/').map(decodeURIComponent);}catch{parts=['overview'];}const [page,id,key]=parts;document.getElementById('breadcrumb').textContent=names[page]||names.overview;const nav=page==='record'?'sources':page==='decision'?'decisions':page||'overview';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===nav)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  if(page==='sources')sources(id);else if(page==='record')record(id,key);else if(page==='metrics')metricPage(id);else if(page==='agents')agentPage(id);else if(page==='processes')processPage(id);else if(page==='decision')decision(id);else if(page==='decisions')decisions();else if(page==='delivery')delivery();else overview();window.scrollTo(0,0);
}
document.getElementById('cutoff').textContent=D.metadata.as_of.replace('T',' · ').replace('Z',' UTC');
window.addEventListener('hashchange',route);route();
