# Generated by Django 5.2.17 on 2026-09-23 02:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=80)),
                ('mode', models.CharField(default='rules', max_length=30)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(default=list)),
                ('output', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('source_fingerprint', models.CharField(blank=True, max_length=128)),
                ('model_invoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('kind', models.CharField(choices=[('individual', 'Particular'), ('fleet', 'Flotilla')], default='individual', max_length=12)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FleetContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('expired', 'Vencido'), ('cancelled', 'Cancelado')], default='draft', max_length=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_contracts', to='workshop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(default='pieza', max_length=30)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('reserved', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='part_stock_nonnegative'), models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='part_reserved_nonnegative'), models.CheckConstraint(condition=models.Q(('stock__gte', models.F('reserved'))), name='part_reservation_covered')],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('stale', 'Obsoleta')], default='pending', max_length=12)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('fingerprint', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='workshop.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ordered', 'Pedida'), ('partial', 'Parcial'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='workshop.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(blank=True, max_length=32)),
                ('vin', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='workshop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TowService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('assigned', 'Asignado'), ('en_route', 'En camino'), ('arrived', 'En sitio'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='requested', max_length=12)),
                ('operator_name', models.CharField(blank=True, max_length=150)),
                ('safety_reference', models.CharField(blank=True, max_length=200)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tow_services', to='workshop.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('completed', 'Atendida'), ('cancelled', 'Cancelada')], default='scheduled', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='workshop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('intake', 'Recepción'), ('inspection', 'Inspección'), ('awaiting_approval', 'Espera autorización'), ('approved', 'Autorizada'), ('in_progress', 'En trabajo'), ('waiting_parts', 'Espera refacciones'), ('quality', 'Calidad'), ('ready', 'Lista'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada')], default='intake', max_length=24)),
                ('complaint', models.TextField()),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='workshop.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Entrada'), ('consume', 'Consumo'), ('return', 'Devolución'), ('adjustment', 'Ajuste')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='workshop.part')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.purchaseorder')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Autorizada'), ('rejected', 'Rechazada'), ('superseded', 'Sustituida')], default='draft', max_length=12)),
                ('approval_name', models.CharField(blank=True, max_length=150)),
                ('approval_reference', models.CharField(blank=True, max_length=200)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Aprobada'), ('fail', 'Rechazada')], max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_checks', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=12)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='workshop.vehicle')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=120)),
                ('result', models.CharField(choices=[('okay', 'Correcto'), ('watch', 'Vigilar'), ('urgent', 'Urgente')], max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspections/%Y/%m/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('dismissed', 'Descartada')], default='open', max_length=16)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_task', to='workshop.proposal')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_tasks', to='workshop.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='workshop_au_entity__060b9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='workshop.invoice')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('received', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshop.part')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='workshop.purchaseorder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_line_quantity_positive'), models.CheckConstraint(condition=models.Q(('received__gte', 0)), name='purchase_line_received_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('received'))), name='purchase_line_received_bounded')],
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('labor', 'Mano de obra'), ('part', 'Refacción'), ('service', 'Servicio')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.part')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='workshop.quote')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_line_quantity_positive')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('consumed', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('returned', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='workshop.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='workshop.workorder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('work_order', 'part'), name='uniq_order_part_reservation'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='reservation_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('consumed__gte', 0)), name='reservation_consumed_nonnegative'), models.CheckConstraint(condition=models.Q(('returned__gte', 0)), name='reservation_returned_nonnegative'), models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('consumed'))), name='reservation_consumed_bounded'), models.CheckConstraint(condition=models.Q(('consumed__gte', models.F('returned'))), name='reservation_returned_bounded')],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('work_order', 'version'), name='uniq_quote_order_version'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('work_order',), name='uniq_approved_quote_order'),
        ),
    ]
