# Generated by Django 5.2.17 on 2026-10-01 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_automation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('order', 'Orden de trabajo'), ('service', 'Hoja de servicio')], max_length=12)),
                ('photo', models.ImageField(upload_to='document-captures/%Y/%m/')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'En cola de lectura'), ('reading', 'Leyendo fotografía'), ('review', 'Por revisar'), ('confirmed', 'Revisado para exportar')], db_index=True, default='pending', max_length=12)),
                ('raw_text', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict)),
                ('reading_note', models.CharField(blank=True, max_length=350)),
                ('reading_token', models.CharField(blank=True, max_length=32)),
                ('reading_started_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
