# Generated by Django 5.2.17 on 2026-10-07 07:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_documentcapture_application_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoQuoteBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='quoteline',
            name='source_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='workshop.capturedservice'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'source_service'), name='uniq_quote_photo_service'),
        ),
        migrations.AddField(
            model_name='photoquotebatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoquotebatch',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photo_batches', to='workshop.quote'),
        ),
    ]
