const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const input = JSON.parse(fs.readFileSync(0, 'utf8'));
  const browser = await chromium.launch({headless:true,channel:process.env.MILENIO_QA_BROWSER || 'chrome'});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  await context.addCookies([{name:input.cookie_name,value:input.cookie,url:input.origin}]);
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => {if(response.status() >= 400 && !response.url().endsWith('/favicon.ico')) errors.push(response.status()+': '+response.url());});
  await page.goto(input.origin+'/commercial/');
  await page.getByRole('heading',{name:'Empresas y seguimiento'}).waitFor();
  if(await page.locator('.crm-metrics').evaluate(node=>getComputedStyle(node).display)!=='grid')throw new Error('Commercial styles did not load');
  await page.screenshot({path:path.join(input.output,'crm-desktop.png'),fullPage:true});
  await page.getByRole('link',{name:'[FICTICIA] Reparto Ejemplo',exact:true}).click();
  await page.getByRole('heading',{name:'Compatible confirmado',exact:true}).waitFor();
  const duplicateIds = await page.locator('[id]').evaluateAll(nodes => {const ids=nodes.map(n=>n.id); return ids.filter((id,i)=>ids.indexOf(id)!==i);});
  if (duplicateIds.length) throw new Error('Duplicate IDs: '+duplicateIds.join(','));
  await page.getByText('Registrar conversación, respuesta o baja',{exact:true}).click();
  await page.locator('[name="interaction-kind"]').selectOption('reply');
  await page.locator('[name="interaction-summary"]').fill('Respuesta ficticia comprobada desde navegador.');
  await page.locator('form').filter({has:page.locator('[name="interaction-kind"]')}).getByRole('button',{name:'Guardar',exact:true}).click();
  await page.getByText('Registro guardado.',{exact:true}).waitFor();
  await page.getByText('Respuesta ficticia comprobada desde navegador.',{exact:true}).waitFor();
  await page.getByText('Sin fecha asignada',{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(input.output,'crm-mobile.png'),fullPage:true});
  const crmOverflow = await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
  if(crmOverflow) throw new Error('CRM mobile overflow');
  if(input.site_origin){
    await page.goto(input.site_origin);
    await page.locator('#vehicle').fill('Pickup gasolina 2020');
    await page.locator('#need').fill('Revisión & mantenimiento');
    await page.getByRole('button',{name:'Preparar mensaje de WhatsApp'}).click();
    const href=await page.locator('#whatsapp-link').getAttribute('href');
    if(!href.startsWith('https://wa.me/526648201966?text=')||!decodeURIComponent(href).includes('Revisión & mantenimiento'))throw new Error('WhatsApp message invalid');
    const siteOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1);
    if(siteOverflow)throw new Error('Site mobile overflow');
    await page.screenshot({path:path.join(input.output,'site-mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(input.site_origin);
    await page.screenshot({path:path.join(input.output,'site-desktop.png'),fullPage:true});
  }
  await browser.close();
  if(errors.length)throw new Error(errors.join('\n'));
  console.log(JSON.stringify({status:'passed',checks:['CRM desktop and mobile','no duplicate form IDs','interaction saved with CSRF','reply cancels next action','site mobile and desktop','WhatsApp target and encoding','no horizontal overflow','no JavaScript errors']}));
})().catch(error=>{console.error(error.message);process.exitCode=1;});
