# Generated by Django 5.2.17 on 2026-10-02 01:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0003_automation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(choices=[('identity', 'Identidad'), ('vehicles', 'Vehículos y combustible'), ('need', 'Necesidad'), ('contact', 'Contacto'), ('coverage', 'Cobertura de grúa'), ('website', 'Texto de sitio')], max_length=30, verbose_name='Tipo de evidencia')),
                ('source_url', models.URLField(blank=True, verbose_name='Fuente pública')),
                ('source_note', models.CharField(blank=True, max_length=240, verbose_name='Fuente directa / referencia')),
                ('excerpt', models.TextField(verbose_name='Hecho o fragmento observado')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de consulta')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Revisado por una persona')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('source', models.CharField(max_length=40)),
                ('query', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Empresa')),
                ('domain', models.CharField(blank=True, max_length=253, null=True, unique=True, verbose_name='Dominio empresarial')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('city', models.CharField(default='Tijuana', max_length=100, verbose_name='Ciudad')),
                ('segment', models.CharField(blank=True, max_length=120, verbose_name='Segmento')),
                ('source', models.CharField(choices=[('google_maps', 'Google / Maps'), ('canacintra', 'CANACINTRA'), ('social', 'Facebook / Instagram'), ('linkedin', 'LinkedIn'), ('referral', 'Referencia'), ('website', 'Sitio empresarial'), ('manual', 'Captura directa')], default='manual', max_length=40, verbose_name='Canal de descubrimiento')),
                ('source_url', models.URLField(blank=True, verbose_name='URL de descubrimiento')),
                ('identity_confirmed', models.BooleanField(default=False, verbose_name='Identidad empresarial revisada')),
                ('stage', models.CharField(choices=[('research', 'Investigación'), ('ready', 'Listo para explorar'), ('conversation', 'En conversación'), ('qualified', 'Necesidad confirmada'), ('proposal', 'Propuesta'), ('pilot', 'Primer servicio'), ('active', 'Cliente recurrente'), ('lost', 'Cerrado sin venta'), ('suppressed', 'No contactar')], db_index=True, default='research', max_length=20)),
                ('next_action', models.CharField(blank=True, max_length=240, verbose_name='Próxima acción')),
                ('next_action_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de seguimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_demo', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.researchbatch')),
                ('operational_customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_action_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('note', 'Nota interna'), ('sent', 'Contacto realizado'), ('reply', 'Respuesta recibida'), ('meeting', 'Conversación / visita'), ('bounce', 'Correo rebotado'), ('optout', 'Pidió no contactar')], max_length=20, verbose_name='Resultado')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del evento')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='commercial.salesaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FleetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel', models.CharField(choices=[('unknown', 'Por confirmar'), ('gasoline', 'Gasolina'), ('mixed', 'Mixta'), ('diesel', 'Diésel'), ('electric', 'Eléctrica'), ('hybrid', 'Híbrida')], default='unknown', max_length=20, verbose_name='Combustible')),
                ('vehicle_type', models.CharField(choices=[('unknown', 'Por confirmar'), ('light', 'Autos / pickups / vans'), ('truck', 'Camiones')], default='unknown', max_length=20, verbose_name='Tipo de unidades evaluadas')),
                ('total_units', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades totales conocidas')),
                ('compatible_units', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades ligeras a gasolina confirmadas')),
                ('need_confirmed', models.BooleanField(default=False, verbose_name='Necesidad confirmada')),
                ('towing_confirmed', models.BooleanField(default=False, verbose_name='Despacho confirmó capacidad y cobertura para estas unidades')),
                ('need_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='need_profiles', to='commercial.evidence')),
                ('towing_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tow_profiles', to='commercial.evidence')),
                ('vehicle_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_profiles', to='commercial.evidence')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='commercial.salesaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='commercial.salesaccount'),
        ),
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='Nombre / área')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo empresarial')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono empresarial')),
                ('source_url', models.URLField(blank=True, verbose_name='Fuente del contacto')),
                ('source_note', models.CharField(blank=True, max_length=240, verbose_name='Fuente directa')),
                ('published_business', models.BooleanField(default=False, verbose_name='Canal empresarial publicado o proporcionado por la empresa')),
                ('deliverability', models.CharField(choices=[('unknown', 'Sin verificar'), ('confirmed', 'Confirmado por respuesta / empresa'), ('bounced', 'Rebotó')], default='unknown', max_length=20, verbose_name='Estado del correo')),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='commercial.salesaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_audit_events', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.salesaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, verbose_name='Oportunidad')),
                ('service', models.CharField(choices=[('mechanics', 'Mecánica'), ('towing', 'Grúa')], max_length=20, verbose_name='Servicio')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe estimado MXN (si se conoce)')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('won', 'Ganada'), ('lost', 'Perdida')], default='open', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='commercial.salesaccount')),
                ('tow_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.towservice')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='workshop.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=240)),
                ('emails', models.JSONField(default=list)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='suppression', to='commercial.salesaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('scope', models.TextField(verbose_name='Alcance y unidades')),
                ('terms', models.TextField(verbose_name='Condiciones, vigencia y exclusiones')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe MXN')),
                ('valid_until', models.DateField(verbose_name='Vigencia')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_reference', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='commercial.salesopportunity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'revision'), name='unique_sales_proposal_revision')],
            },
        ),
    ]
