# Generated by Django 5.2.17 on 2026-10-02 01:59

import django.db.models.deletion
from django.db import migrations, models


def reconcile_existing_states(apps, schema_editor):
    """Do not infer recurrence or an exact historical service authorization."""
    alias = schema_editor.connection.alias
    Account = apps.get_model('commercial', 'SalesAccount')
    Opportunity = apps.get_model('commercial', 'SalesOpportunity')
    Proposal = apps.get_model('commercial', 'SalesProposal')
    Account.objects.using(alias).filter(stage='active').update(stage='recurrence_pending')
    for opportunity in Opportunity.objects.using(alias).exclude(status='lost').iterator():
        latest = Proposal.objects.using(alias).filter(opportunity_id=opportunity.pk).order_by('-revision').first()
        status = 'open'
        if latest:
            status = 'won' if latest.accepted_at and latest.acceptance_reference.strip() else 'pending_acceptance'
        Opportunity.objects.using(alias).filter(pk=opportunity.pk).update(status=status)
    # service_proposal stays NULL: a linked order alone does not identify which
    # revision its operator used. Existing proposal acceptances remain intact.


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaccount',
            name='branch',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sucursal / base'),
        ),
        migrations.AddField(
            model_name='salesaccount',
            name='recurrence_basis',
            field=models.CharField(choices=[('pending', 'Por confirmar'), ('second_order', 'Segunda orden real confirmada'), ('current_plan', 'Plan vigente confirmado')], default='pending', max_length=20, verbose_name='Base de recurrencia'),
        ),
        migrations.AddField(
            model_name='salesaccount',
            name='recurrence_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_accounts', to='commercial.evidence', verbose_name='Evidencia revisada de recurrencia'),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='service_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_services', to='commercial.salesproposal', verbose_name='Propuesta aceptada para el servicio vinculado'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='topic',
            field=models.CharField(choices=[('identity', 'Identidad'), ('vehicles', 'Vehículos y combustible'), ('need', 'Necesidad'), ('contact', 'Contacto'), ('coverage', 'Cobertura de grúa'), ('recurrence', 'Segunda orden o plan vigente'), ('website', 'Texto de sitio')], max_length=30, verbose_name='Tipo de evidencia'),
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=253, null=True, verbose_name='Dominio empresarial'),
        ),
        migrations.AlterField(
            model_name='salesaccount',
            name='stage',
            field=models.CharField(choices=[('research', 'Investigación'), ('ready', 'Listo para explorar'), ('conversation', 'En conversación'), ('qualified', 'Necesidad confirmada'), ('proposal', 'Propuesta'), ('pilot', 'Primer servicio'), ('recurrence_pending', 'Recurrencia por confirmar'), ('active', 'Cliente recurrente'), ('lost', 'Cerrado sin venta'), ('suppressed', 'No contactar')], db_index=True, default='research', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesopportunity',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('pending_acceptance', 'Revisión pendiente de aceptación'), ('won', 'Ganada'), ('lost', 'Perdida')], default='open', max_length=20),
        ),
        # Reverse schema migration does not reconstruct previous business labels.
        # Restore the pre-migration backup if that exact historical state is needed.
        migrations.RunPython(reconcile_existing_states, migrations.RunPython.noop),
    ]
