# Generated by Django 5.2.17 on 2026-10-07 03:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_acceptance_branch_recurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailWorkerLease',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=36)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('connected', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('auto_reply', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(null=True)),
                ('last_tick', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=240)),
                ('holidays', models.JSONField(default=list)),
                ('site_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('public_assets_confirmed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('state', models.CharField(default='active', max_length=24)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mail_enrollment', to='commercial.salesaccount')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.businesscontact')),
            ],
        ),
        migrations.CreateModel(
            name='MailInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=128, unique=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('rfc_id', models.CharField(blank=True, max_length=500)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(max_length=24)),
                ('human_reply', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='commercial.mailenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=16)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('provider_id', models.CharField(blank=True, max_length=128)),
                ('thread_id', models.CharField(blank=True, max_length=128)),
                ('reply_to_id', models.CharField(blank=True, max_length=500)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='commercial.mailenrollment')),
                ('inbound', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response', to='commercial.mailinbound')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'cold')), fields=('enrollment', 'step'), name='mail_unique_cold_step')],
            },
        ),
    ]
