# Generated by Django 5.2.17 on 2026-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_mailworkerlease_mailbox_mailenrollment_mailinbound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailenrollment',
            name='manual_control',
            field=models.BooleanField(default=False),
        ),
    ]
