# Generated by Django 5.2.17 on 2026-10-07 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_mailenrollment_manual_control'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.salesaccount')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.agentcredential')),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.mailinbound')),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='commercial.mailmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationClaim',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='commercial.salesaccount')),
                ('expires_at', models.DateTimeField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.agentcredential')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commercial.agentcredential')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credential', 'request_id'), name='agent_request_unique')],
            },
        ),
    ]
